DROP TABLE ENROLLMENT;
DROP TABLE COURSE;


CREATE TABLE ENROLLMENT(id int  AUTO_INCREMENT  PRIMARY KEY,name varchar(100));
CREATE TABLE COURSE(cid int AUTO_INCREMENT primary key,coursename varchar(100),id int,FOREIGN KEY (id) REFERENCES ENROLLMENT(id));
