DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT(deptid int AUTO_INCREMENT primary key,deptname varchar(100));
CREATE TABLE EMPLOYEE(id int  AUTO_INCREMENT  PRIMARY KEY,name varchar(100),gender varchar(7),deptid int,FOREIGN KEY (deptid) REFERENCES DEPARTMENT(deptid));

